### PR TITLE
Use whatever temp name is provided by tmp package

### LINKED ISSUE #7: When initial try fails, retry fails with "unique tmp filename" error
```
C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\dist\bin\ns:116
  throw err;
  ^

Error: Could not get a unique tmp filename, max tries reached
    at _getTmpNameSync (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\node_modules\tmp\lib\tmp.js:198:9)
    at Object._createTmpDirSync [as dirSync] (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\node_modules\tmp\lib\tmp.js:328:14)
    at Object.<anonymous> (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\dist\bin\ns:111:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
```

### PR DESCRIPTION
**Pull request by OlliV**
When opts.name is set and the temp file already exists, then tmp only retries with the same name and doesn't regenerate a new temporary file name. The issue can be fixed by using opts.template instead, which should also make the use of md5 redundant in ns tmp file naming.

Fixes #7

### CODE REVIEW

**Comment by leo** [comment]
Awesome idea! :blush: But please check if md5 is being used somewhere else. And if not, please remove it from the dependency list.

**Comment by OlliV** [comment]
Correct, it's unnecessary now.

**Comment by leo** [comment]
Perfect. Thank you so much! 🚀

**Comment by leo** [comment]
Quick note: The PR introduced a bug that simply created the temp dir next to the original dir (not within the OS' global tmp directory). Fixed in https://github.com/zeit/now-serve/commit/b90cbac6f23c585b65e1c1d4cf909f602eafb0dd

**Pull request merged**
